controller:
  replicaCount: 2

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb # or elb/classic if needed

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
