apiVersion: kops.k8s.io/v1beta2
kind: Cluster
metadata:
  name: prod-eu-north-1.k8s.local
spec:
  kubernetesVersion: 1.31.4
  cloudProvider: aws
  region: eu-north-1

  # Minimal public topology
  topology:
    masters: public
    nodes: public
    dns:
      type: Public

  api:
    loadBalancer:
      type: Public
      # class: Network  # optional

  networking:
    cilium: {}

  authorization:
    rbac: {}

  iam:
    legacy: false

  # Subnets
  subnets:
    - name: eu-north-1a
      type: Public
      zone: eu-north-1a

  sshAccess:
    - 0.0.0.0/0  # tighten later

  apiAccess:
    - 0.0.0.0/0  # tighten later

  additionalTags:
    environment: test
