replicaCount: 2
namespace: dev # Namespace where resources will be deployed

image:
  repository: noeldevops/spring-app
  tag: "5"
  pullPolicy: IfNotPresent
  pullSecret: my-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: spring.mydomain.com
  path: /

mongodb:
  username: admin
  password: password123
  database: springdb
  storage: 10Gi

awsSecrets:
  enabled: true
  secretName: mongodb-credentials   # AWS Secrets Manager secret name
  k8sSecretName: db-secret          # K8s secret name synced from AWS
  serviceAccounts:
    springApp:
      name: spring-app-sa
      annotations: {}
      # Example for EKS IRSA:
      # annotations:
      #   eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/MySecretsRole
    mongodb:
      name: mongodb-sa
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::719136959080:policy/EKSSecretsManagerPolicy
  providerClassName: aws-secrets-mongodb