# Fluent Bit - DEMO values (lightweight DaemonSet)
# Note: update http_passwd before installing (see README)

backend:
  type: es
  es:
    host: elasticsearch-master
    port: 9200
    scheme: https
    index: fluentbit
    type: _doc
    replace_dots: true
    logstash_format: true
    http_user: elastic
    # Mount password from Kubernetes secret created by Elastic chart
    http_passwd: "${ES_PASSWORD}"
    tls: on
    tls_verify: off

extraEnvs:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password


resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"

serviceAccount:
  create: true
