apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      serviceAccountName: {{ .Values.awsSecrets.serviceAccounts.springApp.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.awsSecrets.providerClassName }}
      containers:
        - name: spring-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongodb-service
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.awsSecrets.k8sSecretName }}
                  key: username
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.awsSecrets.k8sSecretName }}
                  key: password
          resources:
            requests:
              memory: "250Mi"
              cpu: "256m"
            limits:
              memory: "510Mi"
              cpu: "550m"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true