apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
