apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-on-demand
spec:
  role: Node
  subnets:
    - eu-north-1a
  machineType: t3.large
  minSize: 2
  maxSize: 3
  rootVolume:
    size: 50
    type: gp3
  image: ubuntu-24.04